-- MultiTalk Diyalog Metinleri Güncelleme
-- Tüm 8 dil x 14 konu (order_number 2-15)
-- Tarih: 2026-02-18
SET NAMES utf8mb4;

-- =============================================
-- İNGİLİZCE (EN) DİYALOGLARI
-- =============================================

-- EN - Yolda (id=11)
UPDATE videos
SET
    subtitle_text = 'Clara: Excuse me, I am new in the city. How can I go to University of London?\nJohn: University of London is on Malet Street.\nClara: Is it far?\nClara: No, it is close. You can walk there. It takes about 15 minutes.\nClara: OK. How can I get to Malet Street?\nJohn: It''s easy. Go straight ahead up to the crossroads on this Street. Turn left at the crossroads and then walk about 500 m until you reach Palace Street. Go past the street and turn right to Longmoore Street. Go. Straight ahead and you will see a park on your right. Turn right at the traffic lights. Go through Vincent Street and turn left at the crossroads to Malet Street. University of London is there.\nClara: OK… Straight ahead, left at the crossroads, straight to Palace Street, then left. Turn right at the lights and… I am confused.\nJohn: Then let''s go there together. Come with me!\nClara: Are you a student?\nJohn: Yes.\nClara: What is your department?\nJohn: English Literature.\nClara: Today is my first day at the university. I am studying English.\nJohn: Good. Do you know the campus well?\nClara: Not yet. How do I get to my building?\nJohn: You can walk there, too. This road leads to the campus. The Department of English is in the School of Foreign Languages, in building C12.\nClara: Thanks a lot for your help!\nJohn: You''re welcome. What''s your name?\nClara: I''m Clara. What''s your name?\nJohn: I''m John.\nClara: Where are you from, John?\nJohn: I''m from here. And you?\nClara: I''m from Cambridge. Where do you live here?\nJohn: I stay in a dorm on Keppel Street. What about you?\nClara: I live in a flat on Museum Street.\nJohn: How old are you?\nClara: I''m 18. And you?\nJohn: I''m 20. We''re here!\nClara: Shall we have a coffee after class?\nJohn: Sure! I''ll give you a call after class. What''s your number?\nClara: Great! My number is 2071484567.\nJohn: I''ll call you. See you!\nClara: See you!'
WHERE
    id = 11;

-- EN - Telefonda (id=12)
UPDATE videos
SET
    subtitle_text = 'Jane: Hello.\nJohn: Hi, Clara.\nJane: Excuse me, who is this?\nJohn: This is John. Who am I talking to?\nJane: This is Jane Feathers.\nJohn: Isn''t this 555 006 7192?\nJane: No, this is 555 006 7182\nJohn: Oh! I''m sorry. It''s the wrong number.\nJane: No problem, goodbye!\nClara: Hello!\nJohn: Clara?\nClara: Yes, this is Clara.\nJohn: Hi, Clara. This is John.\nClara: Hey John! How are you?\nJohn: I am fine, thank you. How are you?\nClara: I''m fine too.\nJohn: Do you have time today?\nClara: Yes, I do.\nJohn: Will you come to the café with me?\nClara: That sounds great! What time?\nJohn: Half past one. Is that good for you?\nClara: Oh, I have a class at that time. My class ends at three. Does three o''clock suit you?\nJohn: Yes, it does. See you at three then.\nClara: See you!'
WHERE
    id = 12;

-- EN - Üniversitede (id=13)
UPDATE videos
SET
    subtitle_text = 'Clara: Hello everyone!\nJohn: Hi! How are you?\nClara: Thanks, I''m fine. And you?\nJohn: I''m fine too. This is my friend Clara. She is from Cambridge.\nLucy: Hello Clara. I am Lucy. I''m from Manchester.\nNick: Hi, Clara. I''m Nick. I am from Derby.\nClara: Nice to meet you.\nNick: How old are you, Clara?\nClara: I''m eighteen. And you?\nNick: Nineteen. But Lucy is twenty.\nJohn: I am older than you. I was born on December 20, 2002. I''m twenty years old.\nClara: Then your zodiac sign is Sagittarius.\nJohn: Exactly. And what is your sign?\nClara: My sign is Aries. I was born in April.\nLucy: Good, I''m a Pisces. I was born in March. So Clara, which department are you studying in?\nClara: I''m studying English Language Teaching. I just enrolled. You?\nLucy: I''m studying at the Faculty of Medicine.\nClara: What semester are you in?\nLucy: Second. And you?\nNick: It''s my second semester in the Linguistics Department.\nClara: I am in my first semester.\nNick: Clara, what do you think about the English Language Teaching Department in London?\nClara: My classmates are good; the environment is very nice... It is good to study here.\nJohn: Oh my God! I''m so late, sorry, I have class at 14.00.\nClara: Bye!\nJohn: See you!'
WHERE
    id = 13;

-- EN - Süpermarkette (id=14)
UPDATE videos
SET
    subtitle_text = 'Clara: Excuse me, where are the potatoes?\nSeller: Over there, in the front, in the vegetable section.\nClara: I looked there but I couldn''t see them.\nSeller: In front on the right, right at the entrance.\nClara: Thanks, let me look again.\nClara: Oh, John, what a nice coincidence!\nJohn: Yes.\nClara: I need to shop urgently. My fridge is empty.\nJohn: I want to buy fresh fruit and vegetables. Is there anything on sale right now?\nClara: Apples are on sale. Fuji apples. £1.80 a kilo.\nJohn: Good, one kilo please! Is there any spinach?\nClara: It''s over there, next to the onions.\nJohn: Thank you very much!\nClara: And did you get everything you wanted?\nJohn: I need a liter of milk, a can of coke and a bottle of water.\nClara: They are in the drinks aisle.\nJohn: Thank you.\nClara: Are you all set?\nJohn: Yes, thank you, that''s all. Do you need anything?\nClara: Hmm. What do I need? Let me check my shopping list. I need a kilo of rice, a bunch of parsley, 250 grams of cheese, 100 grams of salami and a jar of honey.\nJohn: What kind of salami do you want?\nClara: Turkey salami.\nJohn: Salami is next to meat products, rice is next to grains, cheese is in the cheese aisle and parsley is next to vegetables and fruits. Look. Honey is in the sale section. Do you need anything else?\nClara: No, that''s all. Now we can go to the checkout. Luckily, there isn''t a long line at the checkout.\nSeller: Do you want a plastic bag?\nClara: No, I have a bag.\nSeller: 12 Pounds 50 for all of them.\nClara: Here you go. I want to pay by card.\nSeller: Is your card contactless?\nClara: Yes.\nSeller: Hold your card to the POS device.\nSeller: Thank you very much. Have a nice day.\nJohn: Have a nice day!\nSeller: Good afternoon, would you like a bag?\nJohn: Yes, please.\nSeller: 8,75 please. Do you want to pay by card?\nJohn: I would like to pay in cash, please!\nSeller: Your change is 1,25.\nJohn: Thank you.\nClara: The shopping bags are very heavy.\nJohn: I''ll help you home. Give me the bags!\nClara: Are you sure?\nJohn: Yes.\nClara: Thanks a lot for your help.'
WHERE
    id = 14;

-- EN - Evde (id=15)
UPDATE videos
SET
    subtitle_text = 'Clara: Welcome.\nJohn: Thanks for the invitation. Where can I hang my coat?\nClara: In the cupboard here.\nJohn: Thank you.\nClara: Please sit down, rest.\nJohn: Thank you.\nClara: Would you like to have a drink?\nJohn: I can have a coffee.\nClara: With or without milk?\nJohn: Without milk.\nClara: OK, I''ll get it right away. This is your black coffee and this is my coffee with milk.\nJohn: Oh, thank you.\nClara: You''re welcome!\nJohn: How big is the apartment?\nClara: 80 square metres.\nJohn: Isn''t it too big for you alone? How many rooms does it have?\nClara: Not at all. This flat is perfect for me. It is very nice and quiet. It has a lounge, two bedrooms and a kitchen. It also has a bathroom and a balcony.\nJohn: Wow, it''s great! How is the location?\nClara: It is very central. There is a bus stop and a shopping centre nearby.\nJohn: Do you own the flat?\nClara: No, I pay rent.\nJohn: Is it expensive? How much do you pay a month?\nClara: No, it is cheap. The rent is £1500 and the monthly fee is about £80.\nJohn: It''s not expensive and the flat is nice. It is on the 4th floor but there is no lift. That''s why it''s so cheap. Can I have a look around the flat?\nClara: Sure!\nClara: This is the corridor. Unfortunately, it''s very narrow. There are two rooms here on the right.\nJohn: The rooms are quite bright.\nClara: Yes, that''s right. There''s a big living room opposite this one.\nJohn: The living room has a balcony.\nClara: Yes, but it''s not big.\nJohn: Is this the kitchen?\nClara: Yes, the kitchen is useful and has a view of the river.\nJohn: Is this the bathroom?\nClara: Yes, small but bright.\nJohn: Does the house have a garage?\nClara: Yes, each flat in this apartment block has its own garage.\nJohn: Is the flat well heated?\nClara: Yes, this house is south facing and well insulated.\nJohn: The flat is very nice. It has everything you need.\nClara: Exactly, I am very happy with this flat.\nJohn: Now it''s time to eat. Are you hungry? I know a good restaurant nearby. Shall we have dinner together?\nClara: I''m starving. My stomach is rumbling.\nJohn: Come on then, let''s go eat!'
WHERE
    id = 15;

-- EN - Restoranda (id=16)
UPDATE videos
SET
    subtitle_text = 'John: We''re finally here. Let''s go inside.\nWaiter: Good afternoon, welcome to our restaurant. Do you have a reservation?\nJohn: No, I''m afraid not. Do you have a free table for two?\nWaiter: Yes, no problem. Where would you like to sit?\nJohn: By the window, please.\nWaiter: Unfortunately, the tables by the window are reserved.\nClara: OK, a table at the entrance is fine for us.\nWaiter: Wait a minute! Yes, the table at the entrance is still empty. Please come in! Here is the one just round the corner. Is this table suitable?\nJohn: Yes, it''s fine. Can we have the menu?\nWaiter: Sure. Are you ready to order?\nJohn: Yes, a cabbage soup and pepper steak for me.\nWaiter: Sure. And you? I recommend ravioli, the dish of the day.\nClara: Then I''ll have pumpkin soup and ravioli.\nWaiter: Well, what would you like to drink?\nClara: Coke please!\nJohn: And a tea for me.\nWaiter: Would you like dessert?\nClara: Yes, I would like apple pie.\nJohn: Chocolate pudding for me please.\nWaiter: Coming right away. Anything else?\nClara: No, thank you.\nWaiter: Here you go. And here''s your food. Enjoy your meal!\nJohn: Thank you.\nWaiter: Is there anything missing?\nClara: Could you bring me another napkin?\nJohn: I would like some more bread.\nWaiter: Sure! I''ll bring it right away.\nClara: Thank you.\nWaiter: You''re welcome. Enjoy your meal!\nJohn: Can we get the bill?\nWaiter: Sure! Would you like to pay together or separately?\nJohn: Together, please.\nWaiter: Sure! Will you pay by card?\nJohn: No, we''ll pay in cash.\nWaiter: That''ll be £50.\nJohn: Here you go, keep the change.\nWaiter: Thank you and have a nice day.\nClara: Goodbye.\nJohn: Did you like the food?\nClara: Yes, the food was very tasty. So, what shall we do now?\nJohn: Actually, I have a good idea. My best friend Nick is getting married today. The wedding is at 8pm in Bristol, and I''m invited. Would you like to go to the wedding with me?\nClara: Sure, I would love to go. But what am I going to wear to the wedding? I need a nice dress.\nJohn: And I need a smart suit.'
WHERE
    id = 16;

-- EN - Mağazada (id=17)
UPDATE videos
SET
    subtitle_text = 'Clara: How is the red dress in the window?\nJohn: I like it. Try it on!\nShop assistant: How can I help you?\nClara: I want to try on the red dress in the window.\nShop assistant: What size do you wear?\nClara: I am a size 6.\nShop assistant: Well, come with me! Try this dress on!\nClara: Where can I try it on?\nShop assistant: The fitting rooms are over there. Do you like the dress?\nClara: The colour is OK. But it doesn''t fit me. Do you have a size up?\nShop assistant: There''s one in a size 38.\nClara: OK, I''ll try it on.\nClara: Does the dress fit me?\nJohn: It looks great.\nClara: I like it too. How much is it?\nShop assistant: It is £ 100.\nClara: It''s very stylish. I like the colour. It fits me perfectly. I''ll take this one.\nShop assistant: Do you need anything else?\nJohn: Yes, I''m looking for a suit. Where are the suits?\nShop assistant: On the second floor.\nJohn: This suit is stylish but it costs £ 300. It''s too much. Maybe I can find something cheaper. Oh, there''s a discount there. This suit is very nice. But it won''t fit me, it''s too tight. Excuse me, do you have this suit one size bigger?\nShop assistant: Try this suit here!\nJohn: Thank you. This one is OK.\nShop assistant: Do you need anything else?\nJohn: Do you sell bow ties?\nShop assistant: Of course! Today there is a fifty per cent discount on bow ties and ties.\nJohn: Hmm, I''ll buy a new bow tie for this suit. What colour would suit this one?\nShop assistant: I think this bow tie will fit perfectly.\nJohn: I''ll take it.\nShop assistant: Is there anything else you''re looking for?\nJohn: No, thank you.\nShop assistant: Goodbye!'
WHERE
    id = 17;

-- EN - Garda (id=18)
UPDATE videos
SET
    subtitle_text = 'John: We''re over with our shopping. Now we can go to Bristol.\nClara: OK.\nJohn: The railway station is over there. Now let''s buy our tickets to Bristol. But where can we buy the tickets?\nClara: We can buy tickets from the ticket office.\nJohn: Good afternoon, I would like to buy two tickets to Bristol.\nAttendant: One way?\nJohn: Round trip please.\nAttendant: When do you want to travel?\nJohn: We would like to catch the first train.\nAttendant: The first train leaves in fifteen minutes.\nJohn: That''s fine with us.\nAttendant: It costs £ 160. Will you pay with a card?\nJohn: No, I''ll pay in cash. Here you go.\nAttendant: Your tickets and £40 change.\nJohn: Thank you! Is the train going to be late?\nAttendant: No, it is going to be on time.\nJohn: Thank you.\nAttendant: Bye!\nAnnouncement: Attention, please! The train for Bristol is leaving!\nClara: The train is leaving soon. Let''s get on the train.\nJohn: Let''s go and find our seats.\nClara: These are our seats.\nAnnouncement: Next Station: Bristol Train Station.\nJohn: Clara, get up, let''s get off here. Now let''s find a suitable hotel. Come, let''s go to the centre.\nClara: Oh, look!\nClara: This hotel looks very nice from the outside.\nJohn: This 5-star hotel in the centre of Bristol must have rooms with a nice view.\nClara: Yes, let''s go in.'
WHERE
    id = 18;

-- EN - Otelde (id=74)
UPDATE videos
SET
    subtitle_text = 'Receptionist: Good afternoon, welcome to Bristol Hotel!\nJohn: Good afternoon, we would like two rooms.\nReceptionist: Sure, how many nights are you going to you stay?\nJohn: Only one night.\nReceptionist: OK. We have a room. Do you want a double room?\nJohn: No, we want two single rooms.\nReceptionist: Is breakfast included?\nJohn: Yes, it is included. And is there internet in the rooms?\nReceptionist: Yes, all rooms have internet, bathroom, telephone, television, fridge and air conditioning.\nJohn: Well, we''ll take the rooms.\nReceptionist: OK, can I have your ID cards?\nJohn: Sure, go ahead.\nReceptionist: Thank you, please fill in this form. Write your name, address, date of birth and nationality.\nJohn: Here you go!\nReceptionist: And sign here!\nJohn: All done.\nReceptionist: How would you like to pay?\nJohn: I would like to pay by credit card. Here you go.\nReceptionist: Payment received. Here are your keys. Your room numbers are 104 and 105.\nJohn: Which floor?\nReceptionist: First floor. It''s on the right when you get off the lift.\nJohn: When is breakfast?\nReceptionist: Breakfast is in the dining room from 7.00 to 10.00. The dining room is on the ground floor. You can request breakfast in the room.\nJohn: Thank you. Can I ask one more thing, what other services are there in the hotel?\nReceptionist: We have a restaurant, bar, hairdressing salon and pool for our guests.\nJohn: Very good. What time do you check out of the room?\nReceptionist: 12.00.\nJohn: Thank you very much.\nReceptionist: You''re welcome.\nJohn: Thank you again.\nReceptionist: Have a good rest. The bellboy will show you to your rooms.\nJohn: Good! Goodbye!\nReceptionist: Goodbye!\nJohn: Wow, what a nice room!\nClara: It''s a great hotel in Bristol! The rooms are very nice, clean and the beds are comfortable. The location is good, just a few metres from Queen Square.\nJohn: And the view from the room is great.\nClara: Let''s have a rest first and then we''ll go for a walk around the city together.\nJohn: Shall we meet at five o''clock?\nClara: Yes, yes, that''s fine.\nJohn: Good, let''s meet at the reception at 5 pm. I''ll see you later.\nClara: Deal, see you later.\nJohn: Time to explore the city. Are you ready for a trip?\nClara: Yes, yes I''m ready.\nJohn: We have enough time to see many places in Bristol.'
WHERE
    id = 74;

-- EN - Şehirde (id=82)
UPDATE videos
SET
    subtitle_text = 'Clara: Where does our trip start? What is Bristol famous for?\nJohn: I looked on the internet and learnt about the touristic places in Bristol. Our city tour starts from the Old City.\nClara: Isn''t it the historical part of Bristol?\nJohn: Exactly. Another tourist attraction of Bristol is the Castle Park. The castle was built in the 11th century.\nClara: Wonderful!\nJohn: But no building in Bristol is as famous as Clifton Suspension Bridge. It was built in 1864.\nClara: And what kind of food is Bristol famous for?\nJohn: The most famous Bristol foods are Easter Biscuits, Shepherd''s Pie, and Mothering Buns. Bristol is one of the most beautiful cities in the UK.\nClara: I completely agree with you.\nJohn: The sun is setting. Let''s hurry and not be late for the wedding. You look great in this outfit.\nClara: Thank you. You look very stylish in this suit, too.\nJohn: Thank you! Are you ready for some fun?\nClara: Yes, I''m ready.\nJohn: Come on, let''s go!'
WHERE
    id = 82;

-- EN - Düğünde (id=90)
UPDATE videos
SET
    subtitle_text = 'Nick: Oh, John, how nice to see you here! You are very welcome.\nJohn: I wish you and your wife eternal happiness.\nClara: Congratulations!\nNick: Thank you very much!\nJohn: We have a present for you.\nNick: Wow, thank you very much.\nClara: John, I love this song\nJohn: Would you like to dance with me?\nClara: I would love to.\nJohn: Whose song is this?\nClara: This is Adele''s "Someone Like You". I like this song very much.\nJohn: The song sounds very nice. What kind of music do you like to listen to?\nClara: I like listening to everything from classical music to pop music. And you? What kind of music do you listen to?\nJohn: Mostly rock music.\nClara: What is your favourite song?\nJohn: There are a lot. One of them is Pink Floyd''s "Wish You Were Here."\nClara: Pink Floyd''s songs are good.\nJohn: OK, I''m going to get myself a drink. Do you want one?\nClara: A cocktail for me please.\nJohn: I''ll get it right away.\nJohn: Here you go!\nClara: Thank you!\nNick: Are you having fun?\nJohn: Yes, we are having a lot of fun.\nNick: How do you guys know each other?\nJohn: We study at the same university.\nNick: How nice!\nClara: And how do you know John?\nNick: We are childhood friends. We grew up together.\nClara: So how did you meet your wife?\nNick: We met through a mutual friend in 2022. We have been together for two years.\nClara: Great!\nNick: Come on, let''s dance.\nClara: We had a really unforgettable evening! I''ve never danced so much in my life! Hey, John, what happened to you?\nJohn: I don''t feel well.\nClara: What''s wrong? Are you in pain?\nJohn: I feel sick.\nClara: You should see a doctor.\nJohn: No, I''m fine.\nClara: What do you mean you''re fine? Come on, John, let''s go to the hospital.'
WHERE
    id = 90;

-- EN - Hastanede (id=98)
UPDATE videos
SET
    subtitle_text = 'Secretary: How can I help you?\nJohn: Hello, my name is John Wilson, here is my identity card!\nSecretary: Please wait here. We will call your name.\nDoctor: John Wilson, please come in. What is your complaint?\nJohn: Hello Doctor. I feel very bad. I am nauseous and dizzy.\nDoctor: For how long?\nJohn: About an hour.\nDoctor: What did you eat or drink?\nJohn: I ate snacks at a wedding and drank too much alcohol.\nDoctor: This may be the cause of your complaints. I would like to examine you in more detail. Please lie down on the stretcher and turn your back towards me. Breathe in and out deeply. Do you have any other complaints?\nJohn: Yes, I feel a little cold.\nDoctor: OK. Let me take your temperature. 37.5 degrees. You don''t have a fever. Please open your mouth. It looks fine. Your throat isn''t red. Let''s take your blood pressure. Open your upper arm. 130/90. Your blood pressure is slightly high. Let''s check your blood counts. I''ll take your blood for a blood test. OK! Press hard on the cotton wool, please!\nDoctor: According to the results of the blood test, you probably have food poisoning. First, we''ll put you on an IV drip. I''m also prescribing you a medicine. Take it twice a day for a week. I am writing you a report for two days.\nJohn: I understand, thank you very much, Doctor!\nDoctor: Get well soon!\nClara: Are you feeling better now, John?\nJohn: Yes, I''m much better. But now we need to find a pharmacy nearby.\nClara: Just a minute, let me look on the Internet. Okay, I found it. The nearest open pharmacy is about 500 metres away.\nJohn: We can go on foot.\nClara: Come, let''s go.\nJohn: We finally got to the pharmacy.'
WHERE
    id = 98;

-- EN - Eczanede (id=106)
UPDATE videos
SET
    subtitle_text = 'Pharmacist: How can I help you?\nJohn: The doctor wrote a prescription. Here is the prescription.\nPharmacist: Let me see if we have this medicine.\nJohn: Thank you, I''ll wait.\nPharmacist: Yes, we have it.\nJohn: How should I use the medicine?\nPharmacist: Let me see the instructions for use. Take the medicine twice a day. One tablet in the morning and the second in the evening. Take these pills for a week.\nJohn: Before or after a meal?\nPharmacist: On an empty stomach.\nJohn: And are there any side effects of the medicine?\nPharmacist: No, but don''t take it for more than a week.\nJohn: Yes. And how many pills are in it?\nPharmacist: There are 25 in a box. Do you need anything else?\nJohn: No, thank you. How much is one box?\nPharmacist: £12 per box.\nJohn: OK, I''ll take it. Here''s my credit card.\nPharmacist: Enter the password, please! Thank you, get well soon.\nJohn: Thank you. Goodbye. It''s already morning. We have to go back to the hotel and check out.\nClara: Check-out time is 12.00. In the meantime, we can stop by a bank and withdraw money.\nJohn: Can''t you withdraw the cash from an ATM?\nClara: Unfortunately. The ATM swallowed my bank card.\nJohn: Then we should go to a bank right away.'
WHERE
    id = 106;

-- EN - Bankada (id=114)
UPDATE videos
SET
    subtitle_text = 'Bank Teller: How can I help you?\nClara: My name is Clara Feathers. The ATM swallowed my bank card.\nBank Teller: Have you repeatedly entered your password incorrectly?\nClara: Yes, I entered the wrong password three times.\nBank Teller: I see, the bank ATM has swallowed your bank card for security reasons. You should have your card cancelled and apply for a new card.\nClara: Okay. So how do I apply for a new bank card and how much does it cost?\nBank Teller: Cancellation is free of charge, but renewing the debit card costs 5 Pounds.\nClara: Okay.\nBank Teller: Do you have your ID card with you? I need your name, address and date of birth.\nClara: Yes, here it is.\nBank Teller: Please fill in and sign this form!\nClara: OK.\nBank Teller: We will send your card to your address.\nClara: When is it going to arrive?\nBank Teller: It will take about two weeks.\nClara: Thank you very much. I have one more request: I want to withdraw money from my account.\nBank Teller: Sure, what is your customer number?\nClara: 123456.\nBank Teller: How much money do you want to withdraw?\nClara: I want to withdraw £ 200.\nBank Teller: OK. Here you go.\nClara: Thank you. Can I also find out my balance?\nBank Teller: Sure! Your current balance is £ 1000.\nClara: Thank you very much.\nBank Teller: Do you have any other requests?\nClara: No, thank you.\nClara: We have taken care of all our business, now it is time to check out of the hotel. The train to London leaves at 12.00.\nJohn: We had a really good time. We can go back home now.'
WHERE
    id = 114;

-- =============================================
-- ALMANCA (DE) DİYALOGLARI
-- =============================================

-- DE - Yolda (id=20) - Dosyada "c" yazıyor, boş bırakıyoruz
UPDATE videos SET subtitle_text = NULL WHERE id = 20;

-- DE - Telefonda (id=21)
UPDATE videos
SET
    subtitle_text = 'Sandra: Hallo.\nAlfred: Hallo, Anna.\nSandra: Entschuldigung, mit wem spreche ich?\nAlfred: Ich bin Alfred. Wer sind Sie?\nSandra: Ich bin Sandra Müller.\nAlfred: Ist das nicht 178 225 55 55?\nSandra: Nein, das ist 178 225 55 45.\nAlfred: Oh, entschuldigen Sie! Ich habe die falsche Nummer gewählt.\nSandra: Kein Problem. Auf Wiederhören!\nAnna: Hallo!\nAlfred: Anna?\nAnna: Ja.\nAlfred: Hallo Anna, ich bin Alfred.\nAnna: Hallo Alfred. Wie geht es dir?\nAlfred: Mir geht es gut, danke. Und dir?\nAnna: Mir geht es auch gut.\nAlfred: Hast du heute Zeit?\nAnna: Ja, habe ich.\nAlfred: Kommst du mit ins Café auf dem Campus?\nAnna: Das wäre toll! Um wie viel Uhr?\nAlfred: Um halb zwei. Passt dir das?\nAnna: Schade, um diese Zeit habe ich Unterricht. Mein Unterricht endet um drei. Passt es dir um drei Uhr?\nAlfred: Ja, das passt. Dann sehen wir uns um drei im Café.\nAnna: Bis dann!'
WHERE
    id = 21;

-- DE - Üniversitede (id=22)
UPDATE videos
SET
    subtitle_text = 'Anna: Hallo alle zusammen!\nAlfred: Grüß dich! Wie geht es dir?\nAnna: Danke, es geht mir gut und dir?\nAlfred: Mir geht es auch gut. Das ist Anna. Sie kommt aus Berlin.\nNina: Hallo Anna, ich heiße Nina. Ich komme aus Bremen.\nHeinz: Hi, Anna, ich bin Heinz. Ich komme aus München.\nAnna: Freut mich.\nHeinz: Wie alt bist du Anna?\nAnna: Ich bin achtzehn Jahre alt. Und du?\nHeinz: Neunzehn. Aber Nina ist zwanzig Jahre alt.\nAlfred: Ich bin älter als ihr. Ich bin am 20. Dezember 2002 geboren. Ich bin zweiundzwanzig Jahre alt.\nAnna: Dann ist dein Sternzeichen Schütze.\nAlfred: Genau. Und was ist dein Sternzeichen?\nAnna: Mein Sternzeichen ist Widder. Ich bin im April geboren.\nNina: Toll, ich bin Fische. Ich bin im März geboren. Und Anna, was studierst du denn?\nAnna: Ich studiere in der Abteilung Deutsch auf Lehramt. Ich bin neu immatrikuliert. Und du?\nNina: Ich studiere an der Medizinischen Fakultät.\nAnna: Im wievielten Semester bist du?\nNina: Im zweiten. Und du?\nHeinz: Ich studiere auch im zweiten Semester Linguistik.\nAnna: Ich bin im ersten Semester.\nHeinz: Anna, wie findest du das Studium in der Abteilung Deutsch auf Lehramt in Paderborn?\nAnna: Meine Kommilitonen und Kommilitoninnen sind nett, das Klima ist sehr angenehm... Es ist schön, dass man hier studiert.\nAlfred: Oh Gott, ich bin zu spät. Entschuldigt mich jetzt, ich habe um 14:00 Uhr eine Vorlesung.\nAnna: Auf Wiedersehen!\nAlfred: Tschüs!'
WHERE
    id = 22;

-- DE - Süpermarkette (id=23)
UPDATE videos
SET
    subtitle_text = 'Anna: Entschuldigung, wo sind die Kartoffeln?\nVerkäufer: Da vorne, in der Gemüseabteilung.\nAnna: Da habe ich schon nachgeschaut, aber ich habe sie nicht gesehen.\nVerkäufer: Doch, sie sind vorne rechts, gleich am Eingang.\nAnna: Danke, ich sehe nochmal nach.\nAnna: Oh, Alfred, was für ein Zufall!\nAlfred: Ja.\nAnna: Ich muss dringend einkaufen. Mein Kühlschrank ist leer.\nAlfred: Ich möchte frisches Obst und Gemüse kaufen. Gibt es gerade irgendwelche Angebote?\nAnna: Äpfel sind im Angebot. Bayerische Äpfel. Das Kilo kostet 5 €.\nAlfred: Schön, ein Kilo, bitte! Haben Sie auch Spinat?\nAnna: Die sind dort drüben, neben den Zwiebeln.\nAlfred: Vielen Dank.\nAnna: Hast du alles, was du wolltest?\nAlfred: Ich brauche einen Liter Milch, eine Dose Cola und eine Flasche Wasser.\nAnna: Sie sind bei den Getränken.\nAlfred: Danke.\nAnna: Ist das alles?\nAlfred: Ja, danke, das ist alles. Brauchst du noch etwas?\nAnna: Hm, was brauche ich? Moment, ich schaue auf meine Einkaufsliste. Ich brauche einen Beutel Reis, ein Bund Petersilie, 250 Gramm Käse, 100 Gramm Salami und ein Glas Honig.\nAlfred: Welche Salami möchtest du?\nAnna: Putensalami.\nAlfred: Salami ist bei den Fleischwaren, Reis beim Getreide, Käse bei der Käsetheke und Petersilie bei Obst und Gemüse. Schau mal dort. Honig ist in der „Günstig-Abteilung". Brauchst du noch etwas?\nAnna: Nein, das ist alles. Wir können jetzt zur Kasse gehen. Glücklicherweise gibt es keine lange Schlange an der Kasse.\nVerkäuferin: Möchten Sie eine Tasche?\nAnna: Nein, ich habe eine Tasche.\nVerkäuferin: Das macht zusammen 50 €.\nAnna: Hier, bitte. Ich möchte mit Kreditkarte bezahlen.\nVerkäuferin: Ist Ihre Kreditkarte kontaktlos?\nAnna: Ja.\nVerkäuferin: Halten Sie Ihre Karte ans Kartenlesegerät.\nVerkäuferin: Vielen Dank. Ich wünsche Ihnen einen schönen Tag.\nAlfred: Guten Tag!\nVerkäuferin: Guten Tag! Möchten Sie eine Tüte?\nAlfred: Ja, bitte.\nVerkäuferin: 45,56 €, bitte. Möchten Sie mit Karte bezahlen?\nAlfred: Ich möchte bar bezahlen. Hier, bitte!\nVerkäuferin: 4,44 € zurück.\nAlfred: Vielen Dank.\nAnna: Die Einkaufstüten sind viel zu schwer.\nAlfred: Ich helfe dir, sie bis nach Hause zu tragen. Gib mir die Tüten!\nAnna: Bist du sicher?\nAlfred: Ja.\nAnna: Vielen Dank für deine Hilfe.'
WHERE
    id = 23;

-- DE - Evde (id=24)
UPDATE videos SET subtitle_text = 'Anna: Willkommen!\nAlfred: Vielen Dank für die Einladung. Wo kann ich meinen Mantel aufhängen?\nAnna: Hier in der Garderobe.\nAlfred: Danke.\nAnna: Setz dich und ruh dich aus!\nAlfred: Danke.\nAnna: Möchtest du etwas trinken?\nAlfred: Ich nehme einen Kaffee.\nAnna: Mit oder ohne Milch?\nAlfred: Ohne Milch.\nAnna: Okay, ich bringe ihn sofort. Das ist dein Kaffee ohne Milch, und das ist mein Kaffee mit Milch.\nAlfred: Oh, danke schön.\nAnna: Gern geschehen!\nAlfred: Wie groß ist die Wohnung?\nAnna: 100 Quadratmeter.\nAlfred: Ist sie nicht zu groß für dich allein? Wie viele Zimmer hat sie?\nAnna: Nein, sie ist perfekt für mich. Sie ist sehr schön und ruhig. Sie hat ein Wohnzimmer, zwei Schlafzimmer und eine Küche. Außerdem gibt es ein Bad und einen Balkon.\nAlfred: Oh, toll! Wie ist die Lage?\nAnna: Sehr zentral. In der Nähe gibt es eine Straßenbahnhaltestelle und ein Einkaufszentrum.\nAlfred: Gehört dir die Wohnung?\nAnna: Nein, ich wohne zur Miete.\nAlfred: Ist sie teuer? Wie viel zahlst du im Monat?\nAnna: Nein, sie ist günstig. Die Miete beträgt 800 €, und die Nebenkosten liegen bei etwa 200 € im Monat.\nAlfred: Das ist nicht teuer, und die Wohnung ist schön. Sie liegt im 4. Stock, aber es gibt keinen Aufzug – deshalb ist sie so günstig. Kann ich die Wohnung besichtigen?\nAnna: Natürlich!\nAnna: Dies ist der Flur. Leider ist er ziemlich schmal. Hier rechts sind zwei Zimmer.\nAlfred: Di